### ISSUE TITLE
JSON objects not recognized

### ISSUE THREAD

**Issue by unison3** [roman01la/javascript-to-clojurescript#10]
I am not an advanced developer otherwise I would attempt a fix myself...

Through trial and error using your amazing translator, I whittled down one of the possible reasons why the large block of js code I tried was not working, it seems to not recognise the JSON formatting, as follows;

`const assetData = {
    "type": "MyType",
    "item": mydata
};`

It would be great if you could add a translation rule to deal with JSON

Keep up the good work

Thanks

**Comment by roman01la** [comment]
works great
```
const assetData = { "type": "MyType", "item": mydata };
(def assetData #js {:type "MyType", :item mydata})
```
