### ISSUE TITLE
ForOfStatement is not implemented

### ISSUE THREAD

**Issue by rberger** [roman01la/javascript-to-clojurescript#18]
Just want to say that this tool has saved me time and time again. Really appreciate it existing.
Hope you have the time and interest to keep evolving it. 

Here's something that popped up as a limitation for me.  `Error: ForOfStatement is not implemented`
A sample of code that triggered it
```
  var deviceId;
  for (deviceInfo of deviceInfos) {
    if (deviceInfo.kind === 'videoinput' && deviceInfo.label === 'Reincubate Camo') {
      deviceId = deviceInfo.deviceId
      break;
    }
  }
```

**Comment by roman01la** [comment]
Thanks! Since there's no equivalent language construct in ClojureScript I don't think it's possible to translate `for...of` loop into something that could be done in cljs w/o additional dependencies.
