### ISSUE TITLE
No translation for with "of"

### ISSUE THREAD

**Issue by avelino** [roman01la/javascript-to-clojurescript#6]
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

```javascript
const array1 = ['a', 'b', 'c'];
for (const element of array1) {
  console.log(element);
}
```

**Comment by roman01la** [comment]
That's a language feature that doesn't have 1to1 translation with Clojure, we are not gonna address this.
